// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CountyDataLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("age")]
        public Dictionary<string, double> Age { get; set; }

        [JsonProperty("male")]
        public long Male { get; set; }

        [JsonProperty("female")]
        public long Female { get; set; }

        [JsonProperty("deaths")]
        public Deaths Deaths { get; set; }

        [JsonProperty("health")]
        public Dictionary<string, double> Health { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }

        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("education")]
        public Education Education { get; set; }

        [JsonProperty("zipcodes")]
        [JsonConverter(typeof(DecodeArrayConverter))]
        public long[] Zipcodes { get; set; }

        [JsonProperty("lifeexpectancy")]
        public double Lifeexpectancy { get; set; }

        [JsonProperty("avgincome")]
        public long Avgincome { get; set; }

        [JsonProperty("povertyrate")]
        public double Povertyrate { get; set; }

        [JsonProperty("costofliving")]
        public Costofliving Costofliving { get; set; }

        [JsonProperty("landareakm2")]
        public double Landareakm2 { get; set; }

        [JsonProperty("areakm2")]
        public double Areakm2 { get; set; }
    }

    public partial class Costofliving
    {
        [JsonProperty("livingwage")]
        public double Livingwage { get; set; }

        [JsonProperty("foodcosts")]
        public long Foodcosts { get; set; }

        [JsonProperty("medicalcosts")]
        public long Medicalcosts { get; set; }

        [JsonProperty("housingcosts")]
        public long Housingcosts { get; set; }

        [JsonProperty("taxcosts")]
        public long Taxcosts { get; set; }
    }

    public partial class Deaths
    {
        [JsonProperty("suicides")]
        public double Suicides { get; set; }

        [JsonProperty("homicides")]
        public double Homicides { get; set; }

        [JsonProperty("vehicle")]
        public long Vehicle { get; set; }

        [JsonProperty("firearmsuicides")]
        public double Firearmsuicides { get; set; }
    }

    public partial class Education
    {
        [JsonProperty("lessthanhighschool")]
        public double Lessthanhighschool { get; set; }

        [JsonProperty("highschool")]
        public double Highschool { get; set; }

        [JsonProperty("somecollege")]
        public double Somecollege { get; set; }

        [JsonProperty("bachelors")]
        public double Bachelors { get; set; }
    }
}
